config/routes.rb
Myapp::Application.routes.draw do

get 'pages/home' => 'pages#home'
root 'pages#home'

get '/teams' => 'teams#index'
get 'teams/stats' => 'teams#stats'
get '/players/stats' => 'players#stats'
get '/teams/:id' => 'teams#show', as: :team
get '/players/:id' => 'players#show', as: :player
get '/teams/:id/edit' => 'teams#edit', :as => :teams_edit
get '/players' => 'players#index'
patch '/teams/:id' => 'teams#update'
get '/players/:id/edit' => 'players#edit', :as => :players_edit
patch '/players/:id' => 'players#update'
get '/players/stats/new' => 'players#new', :as => :players_new
post '/players' => 'players#create'

get '/stories' => 'stories#index'
get '/stories/:id' => 'stories#show', as: :story
get '/stories/:id/edit' => 'stories#edit', :as => :stories_edit
patch 'stories/:id' => 'stories#update'
get '/stories/blah/new' => 'stories#new', :as => :stories_new
post '/stories' => 'stories#create'

  get "teams/new"
  get "teams/delete"	

  get "stories/index"
  get "stories/show"
  get "stories/new"

  get "stories/delete"

end

app/models/page.rb
class Page < ActiveRecord::Base
has_many :stories
end

app/models/player.rb
class Player < ActiveRecord::Base
	belongs_to :team
	validates_uniqueness_of :name
end




def self.to_csv(options = {})
CSV.generate(options) do |csv|
	csv << column_names
	all.each do |player|
		csv << player.attributes.values_at(*column_names)
	end
	end
	end
	

	def self.import(file)
		spreadsheet = open_spreadsheet(file)
		header = spreadhseet.row(1)
		(2..spreadsheet.last_row).each do |i|
		row = Hash[[header, spreadsheet.row(i)].transpose]
		player = find_byid(row["id"]) || new
		player.attributes = row.to_hash.slice(*accessible_attributes)
		player.save!
	end
	end

	def self.open_spreadsheet(file)
	case File.extname(file.original_filename)
	when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
	else raise "Unknown file type: #{file.original_filename}"
	end
	end

app/models/story.rb
class Story < ActiveRecord::Base
	belongs_to :page
	validates_uniqueness_of :name
end

app/models/team.rb
require 'enumerator'

class Team < ActiveRecord::Base
	has_many :players
	validates_uniqueness_of :name
	require 'enumerator'
	end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	@stories=Story.all
	end

  	def link_to_image(image_path, target_link)
	link_to(image_tag(image_path, :border => "0"), target_link)
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	helper_method :sort_column, :sort_direction  


def index
 @players = Player.all
end

def stats
 @players = Player.order(sort_column + " " + sort_direction)
end

def show
 @player = Player.find(params[:id])
 @team = @player.team
end

def new
  @player = Player.new 
end

def create
  @player = Player.new(player_params)
  if @player.save
    redirect_to(:action => 'index')
  else
   render('new')
  end
end

def edit
   @player = Player.find(params[:id])
end

def update
 @player = Player.find(params[:id])
  if @player.update_attributes(player_params)
     redirect_to(:action => 'show', :id => @player.id)
  else
     render('index')
  end
end

def delete
 @player = Player.find(params[:id])
end

def destroy
end

private

def player_params
 params.require(:player).permit(:name, :age, :gp, :min, :fgm, :fga, :fg_percent, :three_pm, :three_pa, :three_p_percent, :ftm, :fta, :ft_percent,
 :reb, :ast, :stl, :blk, :pts, :pts_thirty_six, :reb_thirty_six, :pps, :plus_minus, :sal_2015, :sal_2016, :sal_2017,
 :ts_percent, :ast_ratio, :to_ratio, :usg, :reb_rate, :per, :va, :ewa, :team_id )
end

def sort_column
 Player.column_names.include?(params[:sort]) ? params[:sort] : "name"
end

def sort_direction
 %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
	@stories=Story.all
  end

  def show
	@story= Story.find(params[:id])
  end

  def link_to_image(image_path, target_link)
	link_to(image_tag(image_path, :border => "0"), target_link)
  end

  def new
	@story=Story.new
  end

  def create
	@story = Story.new(player_params)
	  if @story.save
	    redirect_to(:action => 'index')
	  else
	    render('new')
 	  end
  end

  def edit
	@story= Story.find(params[:id])
  end

  def update
	 @story = Story.find(params[:id])
  if @story.update_attributes(story_params)
     redirect_to(:action => 'show', :id => @story.id)
  else
     render('index')	
  end
  end

  def delete
  end

  private

  def story_params
	params.require(:story).permit(:name, :thumburl, :summary)
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
	helper_method :sort_column, :sort_direction  

def index
 require 'enumerator'
 @teams = Team.all
end

def stats
 @teams = Team.order(sort_column + " " + sort_direction)
end

def show
 @team = Team.find(params[:id])
 @players = @team.players
end

def new
@team = Team.new
end

def create
end

def edit
 @team = Team.find(params[:id])
end

def update
 @team = Team.find(params[:id])
  if @team.update_attributes(team_params)
   redirect_to(:action => 'show', :id => @team.id)
  else
   render('index')
  end
end

def delete
 @team = Team.find(params[:id])
end

def destroy
end

def link_to_image(image_path, target_link)
 link_to(image_tag(image_path, :border => "0"), target_link)
end


private

def team_params
 params.require(:team).permit(:name, :thumburl, :win_loss, :fg_percent, :fg_percent_rank, :three_pa_rank, :three_pfg_percent, 
 :three_pfg_percent_rank, :fta_rank, :ft_percent, :ft_percent_rank, :reb, :reb_rank, :ast, :ast_rank, :tov, :tov_rank, 
 :stlblk_rank, :ppg, :ppg_rank, :ppga, :ppga_rank, :plus_minus, :plus_minus_rank, :pps, :pps_rank, :ts_percent, 
 :ts_percent_rank )
end

def sort_column
 Team.column_names.include?(params[:sort]) ? params[:sort] : "name"
end

def sort_direction
 %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
end

end

app/helpers/application_helper.rb
module ApplicationHelper

def sortable(column, title = nil)
	title ||= column.titleize
	css_class = column == sort_column ? "current #{sort_direction}" : nil
	direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	link_to title, {:sort => column, :direction => direction}, {:class => css_class}
end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<div class="navbar navbar-default">
	<div class="top">
		<div class="navbar-header">
			<h1>Basketball Analytics</h1>
		</div>
		<ul class="nav navbar-nav">
			<li class="active"><a href="/">Home</a></li>
			<li class="active"><a href="/teams">Teams</a></li>
			<li class="active"><a href="/stories">Rumors</a></li>
			<li class="active"><a href="/teams/stats">League Stats</a></li>
			<li class="active"><a href="/players/stats">Player Stats</a></li>
		</ul>
	</div>
</div>
</body>
</html>

app/views/pages/home.html.erb
<! DOCTYPE html>




<html>
<body>

<div class="main">
	<p>Your one stop shop for advanced analytics, salary information and insider NBA rumors</p>
	<img src="http://img1.wikia.nocookie.net/__cb20131015203103/logopedia/images/d/df/121210092244-nba-logo-wordmark-275-wide.story-top.jpg">
</div>


<div class="filler"></div>
<div class="center">
 <div class="col-lg-3">
  <h1>Advanced Analytics for each NBA Team</h1>
   <p>See how each team stacks up against eachother in advanced metrics & each team's salary situation.</p>
    <p style="text-align:center"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Basketball.png"></p>
 </div>
 <div class="col-lg-3">
  <h1>Advanced Analytics for each NBA Player</h1>
   <p>Compare players with advanced stats such as PER, Usage and Estimated Wins Added.</p>
    <p style="text-align:center"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Basketball.png"></p>
 </div>
 <div class="col-lg-3">
  <h1>Insider Trade & Free Agency Rumors</h1>
   <p>Get insider access to all the latest free agency and trade rumors throughout the association.</p>
    <p style="text-align:center"><img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Basketball.png"></p>
 </div>
</div>

</body>
</html>

app/views/players/delete.html.erb
<h1>Players#delete</h1>
<p>Find me in app/views/players/delete.html.erb</p>

app/views/players/edit.html.erb
<!DOCTYPE html>




<div class="main">
	<h1><%=@player.name%></h1>
	<p> EDIT PLAYER INFO </p>
</div>

<div class="team-form">
<%= form_for (@player) do |t| %>

<div class="col-lg-4">

  <br><%= t.label :name %><br>
  <%= t.text_field :name %><br>

  <br><%= t.label :team %><br>
  <%= t.number_field :team_id %><br>

  <br><%= t.label :age %><br>
  <%= t.number_field :age %><br>

  <br><%= t.label :GP %><br>
  <%= t.number_field :gp %><br>

  <br><%= t.label :MPG %><br>
  <%= t.number_field :min %><br>

  <br><%= t.label :FGM %><br>
  <%= t.number_field :fgm %><br>

  <br><%= t.label :FGA %><br>
  <%= t.number_field :fga %><br>

  <br><%= t.label :FG_percent %><br>
  <%= t.number_field :fg_percent %><br>

  <br><%= t.label :Three_PM %><br>
  <%= t.number_field :three_pm %><br>

  <br><%= t.label :Three_PA %><br>
  <%= t.number_field :three_pa %><br>

  <br><%= t.label :Three_P_percent %><br>
  <%= t.number_field :three_p_percent %><br>

  <br><%= t.label :FTA %><br>
  <%= t.number_field :fta %><br>

</div>

<div class="col-lg-4">

  <br><%= t.label :FTM %><br>
  <%= t.number_field :ftm %><br>

  <br><%= t.label :FT_percent %><br>
  <%= t.number_field :ft_percent %><br>

  <br><%= t.label :Reb %><br>
  <%= t.number_field :reb %><br>

  <br><%= t.label :Ast %><br>
  <%= t.number_field :ast %><br>

  <br><%= t.label :Stl %><br>
  <%= t.number_field :stl %><br>

  <br><%= t.label :Blk %><br>
  <%= t.number_field :blk %><br>

  <br><%= t.label :PPG %><br>
  <%= t.number_field :pts %><br>

  <br><%= t.label :pts_thirty_six %><br>
  <%= t.number_field :pts_thirty_six %><br>

  <br><%= t.label :reb_thirty_six %><br>
  <%= t.number_field :reb_thirty_six %><br>

  <br><%= t.label :pps %><br>
  <%= t.number_field :pps %><br>

  <br><%= t.label :plus_minus %><br>
  <%= t.number_field :plus_minus %><br>

  <br><%= t.label :sal_2015 %><br>
  <%= t.number_field :sal_2015 %><br>

</div>
<div class="col-lg-4">

  <br><%= t.label :sal_2016 %><br>
  <%= t.number_field :sal_2016 %><br>

  <br><%= t.label :sal_2017 %><br>
  <%= t.number_field :sal_2017 %><br>

  <br><%= t.label :ts_percent %><br>
  <%= t.number_field :ts_percent %><br>

  <br><%= t.label :ast_ratio %><br>
  <%= t.number_field :ast_ratio %><br>

  <br><%= t.label :to_ratio %><br>
  <%= t.number_field :to_ratio %><br>

  <br><%= t.label :usage %><br>
  <%= t.number_field :usg %><br>

  <br><%= t.label :reb_rate %><br>
  <%= t.number_field :reb_rate %><br>

  <br><%= t.label :PER %><br>
  <%= t.number_field :per %><br>

  <br><%= t.label :VA %><br>
  <%= t.number_field :va %><br>

  <br><%= t.label :EWA %><br>
  <%= t.number_field :ewa %><br>


  <br><%= t.submit %><br>
</div>

<%end%>
</div>

app/views/players/index.html.erb
<!DOCTYPE html>

<html>
<body>



<div class="main">
	<h1>NBA Players Sortable Stats</h1>
	<p>Compare Player Stats and Analytics</p>
	<img src="http://img1.wikia.nocookie.net/__cb20131015203103/logopedia/images/d/df/121210092244-nba-logo-wordmark-275-wide.story-top.jpg">
</div>


<table border="1" style="width:50%">
		<tr>
		<th><%= sortable "name", "Name" %></th>
		<th> Age </th>
		<th> Min </th>
		<th> PTS </th>
		<th> REB </th>	
		</tr>

	<% @players.each do |d| %>	
		<tr>
		<td><%= link_to(d.name, player_path(d)) %></td>
		<td><%= d.age %></td>
		<td><%= d.min %></td>
		<td><%= d.pts %></td>
		<td><%= d.reb %></td>
	<% end %>
		</tr>

app/views/players/new.html.erb
<!DOCTYPE html>



<div class="main">
	<h1><%=@player.name%></h1>
	<p> Add New Player </p>
</div>

<div class="team-form">
<%= form_for (@player) do |t| %>

<div class="col-lg-4">

  <br><%= t.label :name %><br>
  <%= t.text_field :name %><br>

  <br><%= t.label :team %><br>
  <%= t.number_field :team_id %><br>

  <br><%= t.label :age %><br>
  <%= t.number_field :age %><br>

  <br><%= t.label :GP %><br>
  <%= t.number_field :gp %><br>

  <br><%= t.label :MPG %><br>
  <%= t.number_field :min %><br>

  <br><%= t.label :FGM %><br>
  <%= t.number_field :fgm %><br>

  <br><%= t.label :FGA %><br>
  <%= t.number_field :fga %><br>

  <br><%= t.label :FG_percent %><br>
  <%= t.number_field :fg_percent %><br>

  <br><%= t.label :Three_PM %><br>
  <%= t.number_field :three_pm %><br>

  <br><%= t.label :Three_PA %><br>
  <%= t.number_field :three_pa %><br>

  <br><%= t.label :Three_P_percent %><br>
  <%= t.number_field :three_p_percent %><br>

  <br><%= t.label :FTA %><br>
  <%= t.number_field :fta %><br>

</div>

<div class="col-lg-4">

  <br><%= t.label :FTM %><br>
  <%= t.number_field :ftm %><br>

  <br><%= t.label :FT_percent %><br>
  <%= t.number_field :ft_percent %><br>

  <br><%= t.label :Reb %><br>
  <%= t.number_field :reb %><br>

  <br><%= t.label :Ast %><br>
  <%= t.number_field :ast %><br>

  <br><%= t.label :Stl %><br>
  <%= t.number_field :stl %><br>

  <br><%= t.label :Blk %><br>
  <%= t.number_field :blk %><br>

  <br><%= t.label :PPG %><br>
  <%= t.number_field :pts %><br>

  <br><%= t.label :pts_thirty_six %><br>
  <%= t.number_field :pts_thirty_six %><br>

  <br><%= t.label :reb_thirty_six %><br>
  <%= t.number_field :reb_thirty_six %><br>

  <br><%= t.label :pps %><br>
  <%= t.number_field :pps %><br>

  <br><%= t.label :plus_minus %><br>
  <%= t.number_field :plus_minus %><br>

  <br><%= t.label :sal_2015 %><br>
  <%= t.number_field :sal_2015 %><br>

</div>
<div class="col-lg-4">

  <br><%= t.label :sal_2016 %><br>
  <%= t.number_field :sal_2016 %><br>

  <br><%= t.label :sal_2017 %><br>
  <%= t.number_field :sal_2017 %><br>

  <br><%= t.label :ts_percent %><br>
  <%= t.number_field :ts_percent %><br>

  <br><%= t.label :ast_ratio %><br>
  <%= t.number_field :ast_ratio %><br>

  <br><%= t.label :to_ratio %><br>
  <%= t.number_field :to_ratio %><br>

  <br><%= t.label :usage %><br>
  <%= t.number_field :usg %><br>

  <br><%= t.label :reb_rate %><br>
  <%= t.number_field :reb_rate %><br>

  <br><%= t.label :PER %><br>
  <%= t.number_field :per %><br>

  <br><%= t.label :VA %><br>
  <%= t.number_field :va %><br>

  <br><%= t.label :EWA %><br>
  <%= t.number_field :ewa %><br>


  <br><%= t.submit %><br>
</div>

<%end%>
</div>

app/views/players/show.html.erb
<html>
<body>



<div class="main">
	<h1><%=@player.name%></h1>
	<h3><%=@team.name%></h3>
	<p><%=image_tag(@team.thumburl)%> </p>
	<div class="button"><p><%= link_to 'Edit Player', :action => :edit %></p></div>
</div>


<div class="team-rank">

<div class="col-lg-1"></div>
<div class="col-lg-2">

 <p><b>MPG = Minutes per Game</b></p>
 <p><b>PPG = Points per Game</b></p>
 <p><b>+/- = Plus/Minus</b>, averages the points scored versus points scored against for the entire season while that player was on the court</p>
 <p><b>TS% = True Shooting Percentage</b>, what a player's shooting percentage would be if we acconted for free throws and 3-pointers.  TS% = Total Points / [(FGA + (0.44 x FTA)]</p>
 <p><b>PER = Player Efficiency Rating</b>, overall rating of a player's per-minute statistical production.  The league average is 15.00 every season.</p>
 <p><b>VA = Value Added</b>, estimated number of points a player adds to a team's season total above what a 'replacement player' would produce.  VA = ([Minutes * (PER - PRL)] / 67).  PRL (Position Replacement Level) = 11.5 for power forwards, 11.0 for point guards, 10.6 for centers, 10.5 for shooting guards and small forwards.</p>
 <p><b>EWA = Estimated Wins Added</b>, Value Added divided by 30, giving the estimated number of wins a player adds to a team's season total above what a 'replacement player' would produce.</p>
 <p><b>USG = Usage Rate</b>, the number of possessions a player uses per 40 minutes.  USG = {[FGA + FT Att. x 0.44) + (Ast x 0.33) + TO] x 40 x League Pace} divided by (Minutes x Team Pace)</p>

</div>
<div class="col-lg-1"></div>

<div class="col-lg-7">
	<table border="<table border="1" style="width:75%" table align="center">
		<tr>
		<th></th>
		<th> 2015 Salary </th>
		<th> 2016 Salary </th>
		<th> 2017 Salary </th>	
		</tr>


		<tr>
		<td><b><%=@player.name%></b></td>
		<td><%= number_with_delimiter(@player.sal_2015, :delimiter => ',') %></td>
		<td><%= number_with_delimiter(@player.sal_2016, :delimiter => ',') %></td>
		<td><%= number_with_delimiter(@player.sal_2017, :delimiter => ',') %></td>
		</tr>
	</table>



	<table border="<table border="1" style="width:100%" table align="center">

		<tr>
		<th>Age</th> 
		<th>GP</th> 
		<th>MPG</th> 
		<th>PPG</th> 
		<th>FG%</th> 
		<th>3FG%</th> 
		<th>FT%</th> 
		<th>REB</th> 
		<th>AST</th> 
		<th>STL</th> 
		</tr>

		<tr>
		<td><%=@player.age%></td> 
		<td><%=@player.gp%></td> 
		<td><%=@player.min%></td> 
		<td><%=@player.pts%></td> 
		<td><%=@player.fg_percent%></td> 
		<td><%=@player.three_p_percent%></td> 
		<td><%=@player.ft_percent%></td> 
		<td><%=@player.reb%></td> 
		<td><%=@player.ast%></td> 
		<td><%=@player.stl%></td>
		</tr> 
	</table>

	<table border="1" style="width:100%" table align="center">

		<tr>
		<th>PTS/36</th> 
		<th>REB/36</th> 
		<th>PPS</th> 
		<th>+/-</th> 
		<th>TS%</th> 
		<th>AST ratio</th> 
		<th>TO ratio</th> 
		<th>USG</th> 
		<th>REB rate</th> 
		<th>PER</th> 
		<th>VA</th> 
		<th>EWA</th> 
		</tr>

		<tr>
		<td><%=@player.pts_thirty_six%></td> 
		<td><%=@player.reb_thirty_six%></td> 
		<td><%=@player.pps%></td> 
		<td><%=@player.plus_minus%></td> 
		<td><%=@player.ts_percent%></td> 
		<td><%=@player.ast_ratio%></td> 
		<td><%=@player.to_ratio%></td> 
		<td><%=@player.usg%></td> 
		<td><%=@player.reb_rate%></td> 
		<td><%=@player.per%></td> 
		<td><%=@player.va%></td>
		<td><%=@player.ewa%></td>
		</tr> 
	</table>
</div>




</div>
</div>
</div>

app/views/players/stats.html.erb
<!DOCTYPE html>





<div class="main">
	<h1>NBA Players Sortable Stats</h1>
	<p>Compare Player Stats and Analytics</p>
	
	<img src="http://img1.wikia.nocookie.net/__cb20131015203103/logopedia/images/d/df/121210092244-nba-logo-wordmark-275-wide.story-top.jpg">
	<div class="button"><p><%= link_to 'Add New Player', :action => :new %></p></div>
</div>

<div class="team-rank">
<div class="col-lg-1"></div>

<div class="col-lg-2">
 <p><b>MPG = Minutes per Game</b></p>
 <p><b>PPG = Points per Game</b></p>
 <p><b>+/- = Plus/Minus</b>, averages the points scored versus points scored against for the entire season while that player was on the court</p>
 <p><b>TS% = True Shooting Percentage</b>, what a player's shooting percentage would be if we acconted for free throws and 3-pointers.  TS% = Total Points / [(FGA + (0.44 x FTA)]</p>
 <p><b>PER = Player Efficiency Rating</b>, overall rating of a player's per-minute statistical production.  The league average is 15.00 every season.</p>
 <p><b>VA = Value Added</b>, estimated number of points a player adds to a team's season total above what a 'replacement player' would produce.  VA = ([Minutes * (PER - PRL)] / 67).  PRL (Position Replacement Level) = 11.5 for power forwards, 11.0 for point guards, 10.6 for centers, 10.5 for shooting guards and small forwards.</p>
 <p><b>EWA = Estimated Wins Added</b>, Value Added divided by 30, giving the estimated number of wins a player adds to a team's season total above what a 'replacement player' would produce.</p>
 <p><b>USG = Usage Rate</b>, the number of possessions a player uses per 40 minutes.  USG = {[FGA + FT Att. x 0.44) + (Ast x 0.33) + TO] x 40 x League Pace} divided by (Minutes x Team Pace)</p>
 
</div>

<div class="col-lg-1"></div>

 <div class="col-lg-7">
  <table style="width:100%" table align="center">
	<tr>
		<th><b><%= sortable "name", "Name" %></b></th>
		<th><%= sortable "min", "MPG" %></th>
		<th><%= sortable "pts", "PPG" %></th>
		<th><%= sortable "fg_percent", "FG%" %></th>
		<th><%= sortable "three_p_percent", "3P%" %></th>
		<th><%= sortable "ft_percent", "FT%" %></th>
		<th><%= sortable "reb", "REB" %></th>
		<th><%= sortable "ast", "AST" %></th>
		<th><%= sortable "stl", "STL" %></th>
		<th><%= sortable "blk", "BLK" %></th>
		<th><%= sortable "plus_minus", "+/-" %></th>
		<th><%= sortable "ts_percent", "TS%" %></th>
		<th><%= sortable "per", "PER" %></th>
		<th><%= sortable "va", "VA" %></th>	
		<th><%= sortable "ewa", "EWA" %></th>
		<th><%= sortable "usg", "USG" %></th>

	</tr>

	<% @players.each do |t|%>
	
	<tr>
		<td><%= link_to(t.name, player_path(t)) %></td>
		<td><%= t.min %></td>
		<td><%= t.pts %></td>
		<td><%= t.fg_percent %></td>
		<td><%= t.three_p_percent %></td>
		<td><%= t.ft_percent %></td>
		<td><%= t.reb %></td>
		<td><%= t.ast %></td>
		<td><%= t.stl %></td>
		<td><%= t.blk %></td>
		<td><%= t.plus_minus %></td>
		<td><%= t.ts_percent %></td>
		<td><%= t.per %></td>
		<td><%= t.va %></td>
		<td><%= t.ewa %></td>
		<td><%= t.usg %></td>
	</tr>

	<%end%>
  </table>
 </div>
</div>

app/views/stories/delete.html.erb
<h1>Stories#delete</h1>
<p>Find me in app/views/stories/delete.html.erb</p>

app/views/stories/edit.html.erb
<!DOCTYPE html>



<div class="main">
	<h1><%=@story.name%></h1>
	<p> EDIT STORY INFO </p>
</div>

<div class="team-form">
<%= form_for (@story) do |t| %>

<div class="col-lg-4">

  <br><%= t.label :name %><br>
  <%= t.text_field :name %><br>

  <br><%= t.label :thumburl %><br>
  <%= t.text_field :thumburl %><br>

  <br><%= t.label :summary %><br>
  <%= t.text_field :summary %><br>




  <br><%= t.submit %><br>
</div>

<%end%>
</div>

app/views/stories/index.html.erb
<! DOCTYPE html>



<div class="main">
        <h1>Insider Basketball Rumors and Stories</h1>
	<p>Check out all the latest insider NBA stories</p>
	<img src="http://img1.wikia.nocookie.net/__cb20131015203103/logopedia/images/d/df/121210092244-nba-logo-wordmark-275-wide.story-top.jpg">
	<div class="button"><p><%= link_to 'Add New Story', :action => :new %></p></div>
</div>



<div class="team-rank">
<table id="t02" style="width:50%" align="center">

 <tr>
  <td><%= link_to(image_tag("http://img1.imagehousing.com/6/2c3135e357f538e4915a5a36d20f67a5.jpg"), story_path("4")) %></td>
  <td><%= link_to(image_tag("http://img1.imagehousing.com/22/63c2f288332256b268583313070ec008.jpg"), story_path("3")) %></td>
 </tr>

 <tr>
  <td><h2> Dallas implodes in playoffs, management will look to rebuild </h2></td>
  <td><h2> Spurs looking to add Lamarcus Aldridge this offseason </h2></td>
 </tr>

</table>
</div>


<table id="t02" style="width:50%" align="center">

 <tr>
  <td> <%= link_to(image_tag("http://img1.imagehousing.com/49/247d780509134e7fd5503dc466577b86.jpg"), story_path("2")) %></td>
  <td> <%= link_to(image_tag("http://img1.imagehousing.com/17/a81fd8a91a96e7d673f57c4ac06d4447.jpg"), story_path("1")) %></td>
 </tr>

 <tr>
  <td><h2> After the Bulls were eliminated, is Coach Thibs headed out the door? </h2></td>
  <td><h2>With With the emergence of Tristan Thompson, will Kevin Love re-sign in a lesser role? </h2></td>

</table>